### ISSUE TITLE
Concurrent tasks

### ISSUE THREAD

**Issue by jamolkhon** [techyourchance/thread-poster#4]
Could you please provide a (simple) example that executes two long running tasks _simultaneously_ waiting for both finish before outputting results?

**Comment by techyourchance** [comment]
I know it's been a year, but I missed this question. Sorry.
Anyways, for a future reference, you could do it along these lines:

    public void executeTasks() {
        backgroundThreadPoster.post(() -> executeAndWaitForResults());
    }

    @WorkerThread
    private void executeAndWaitForResults() {
        final AtomicReference<Boolean> successA = new AtomicReference<>(false);
        final AtomicReference<Boolean> successB = new AtomicReference<>(false);
        final CountDownLatch countDownLatch = new CountDownLatch(2);
        backgroundThreadPoster.post(() -> {
            try {
                // execute A
                successA.set(true);
            } finally {
                countDownLatch.countDown();
            }
        });
        backgroundThreadPoster.post(() -> {
            try {
                // execute B
                successB.set(true);
            } finally {
                countDownLatch.countDown();
            }
        });
        try {
            countDownLatch.await();
        } catch (InterruptedException e) {
            throw new RuntimeException("unexpected interrupt");
        }
        if (successA.get() && successB.get()) {
            // report both executed successfully
        } else {
           // report at least one failed
        } 
    }
